version: 2

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
    - Deuchnord
  commit-message:
    prefix: chore
    include: scope

  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 5
    target-branch: master
    schedule:
      interval: weekly
    reviewers:
      - Deuchnord
    commit-message:
      prefix: ci
      include: scope
