github:
  prebuilds:
    pullRequestsFromForks: true

vscode:
  extensions:
    - ms-vscode.makefile-tools

tasks:
  - before: pip install -U pip pipenv
    init: pipenv lock --pre && pipenv sync --dev --pre
