github:
  prebuilds:
    pullRequestsFromForks: true

vscode:
  extensions:
    - ms-vscode.makefile-tools
    - editorconfig.editorconfig

tasks:
  - before: pip install -U pip poetry
    init: poetry install
