name: Pull Request Checks

on:
  pull_request:
    branches: [main, features]

jobs:
  semantic-pr:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Code Style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: psf/black@20.8b1
