name: Release library

on:
    release:
        types: [published]


jobs:
    pipy:
        name: Build and release to PyPI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - name: Setup environment
              run: |
                sudo apt update
                python -m pip install --upgrade pip poetry
                sudo apt install ruby
                sudo gem install ronn
            - name: Build package
              run: |
                poetry install
                poetry build
            - name: Publish package
              env:
                POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_PASSWORD }}
              run: |
                poetry publish
