name: Unit tests

on:
  push:
    branches: [main, features]
  pull_request:
    branches: [main, features]

jobs:
  legacy-unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11.0
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'

    name: Legacy unit tests (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip pipenv
        pipenv lock --pre
        pipenv sync --dev
    - name: Unit tests
      run: |
        make legacy-tests

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11.0
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'

    name: Unit tests (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip pipenv
        pipenv lock --pre
        pipenv sync --dev
    - name: Unit tests
      env:
        COVERALLS_PRO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make doctests
        pipenv run coveralls --service=github
